<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>TwoIFClient</RootNamespace>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
    <ApplicationIcon>TwoIF Icon.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="TwoIF Icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Otp.NET" Version="1.4.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OtpLibrary\OtpLibrary.csproj" />
    <ProjectReference Include="..\QRCodeLibrary\QRCodeLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="UriEditorDialog.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

</Project>